import { Key, LOCALE } from '@/enums';

export type HighLightsByLocaleType = {
    [key in Key]?: string[];
};

export type HighLightsType = {
    [key in LOCALE]: HighLightsByLocaleType;
};

export const makeBoldExceptionKeys = [
    Key.Backspace,
    Key.Tab,
    Key.CapsLock,
    Key.Enter,
    Key.ShiftLeft,
    Key.ShiftRight,
    Key.Fn,
    Key.ControlLeft,
    Key.AltLeft,
    Key.MetaLeft,
    Key.Space,
    Key.MetaRight,
    Key.AltRight,
    Key.ArrowLeft,
    Key.ArrowUp,
    Key.ArrowDown,
    Key.ArrowRight
];

export const highlightsConfig: HighLightsType = {
    [LOCALE.EN]: {
        [Key.IntlBackslash]: ['§', '±'],
        [Key.Digit1]: ['1', '!'],
        [Key.Digit2]: ['2', '@'],
        [Key.Digit3]: ['3', '#'],
        [Key.Digit4]: ['4', '$'],
        [Key.Digit5]: ['5', '%'],
        [Key.Digit6]: ['6', '^'],
        [Key.Digit7]: ['7', '&'],
        [Key.Digit8]: ['8', '*'],
        [Key.Digit9]: ['9', '('],
        [Key.Digit0]: ['0', ')'],
        [Key.Minus]: ['-', '_'],
        [Key.Equal]: ['=', '+'],

        [Key.KeyQ]: ['q', 'Q'],
        [Key.KeyW]: ['w', 'W'],
        [Key.KeyE]: ['e', 'E'],
        [Key.KeyR]: ['r', 'R'],
        [Key.KeyT]: ['t', 'T'],
        [Key.KeyY]: ['y', 'Y'],
        [Key.KeyU]: ['u', 'U'],
        [Key.KeyI]: ['i', 'I'],
        [Key.KeyO]: ['o', 'O'],
        [Key.KeyP]: ['p', 'P'],
        [Key.BracketLeft]: ['[', '{'],
        [Key.BracketRight]: [']', '}'],

        [Key.KeyA]: ['a', 'A'],
        [Key.KeyS]: ['s', 'S'],
        [Key.KeyD]: ['d', 'D'],
        [Key.KeyF]: ['f', 'F'],
        [Key.KeyG]: ['g', 'G'],
        [Key.KeyH]: ['h', 'H'],
        [Key.KeyJ]: ['j', 'J'],
        [Key.KeyK]: ['k', 'K'],
        [Key.KeyL]: ['l', 'L'],
        [Key.Semicolon]: [';', ':'],
        [Key.Quote]: ["'", '"'],
        [Key.Backslash]: ['\\', '|'],

        [Key.ShiftRight]: [
            '±',
            '!',
            '@',
            '#',
            '$',
            '%',
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            '~',
            'Z',
            'X',
            'C',
            'V',
            'B'
        ],
        [Key.Backquote]: ['`', '~'],
        [Key.KeyZ]: ['z', 'Z'],
        [Key.KeyX]: ['x', 'X'],
        [Key.KeyC]: ['c', 'C'],
        [Key.KeyV]: ['v', 'V'],
        [Key.KeyB]: ['b', 'B'],
        [Key.KeyN]: ['n', 'N'],
        [Key.KeyM]: ['m', 'M'],
        [Key.Comma]: [',', '<'],
        [Key.Period]: ['.', '>'],
        [Key.Slash]: ['/', '?'],
        [Key.ShiftLeft]: [
            '^',
            '&',
            '*',
            '(',
            ')',
            '_',
            '+',
            'Y',
            'U',
            'I',
            'O',
            'P',
            '{',
            '}',
            'H',
            'J',
            'K',
            'L',
            ':',
            '"',
            '|',
            'N',
            'M',
            '<',
            '>',
            '?'
        ],

        [Key.Space]: [' ']
    },
    [LOCALE.RU]: {
        [Key.IntlBackslash]: ['ё', 'Ё'],
        [Key.Digit1]: ['1', '!'],
        [Key.Digit2]: ['2', '"'],
        [Key.Digit3]: ['3', '№'],
        [Key.Digit4]: ['4', ';'],
        [Key.Digit5]: ['5', '%'],
        [Key.Digit6]: ['6', ':'],
        [Key.Digit7]: ['7', '?'],
        [Key.Digit8]: ['8', '*'],
        [Key.Digit9]: ['9', '('],
        [Key.Digit0]: ['0', ')'],
        [Key.Minus]: ['-', '_'],
        [Key.Equal]: ['=', '+'],

        [Key.KeyQ]: ['й', 'Й'],
        [Key.KeyW]: ['ц', 'Ц'],
        [Key.KeyE]: ['у', 'У'],
        [Key.KeyR]: ['к', 'К'],
        [Key.KeyT]: ['е', 'Е'],
        [Key.KeyY]: ['н', 'Н'],
        [Key.KeyU]: ['г', 'Г'],
        [Key.KeyI]: ['ш', 'Ш'],
        [Key.KeyO]: ['щ', 'Щ'],
        [Key.KeyP]: ['з', 'З'],
        [Key.BracketLeft]: ['х', 'Х'],
        [Key.BracketRight]: ['ъ', 'Ъ'],

        [Key.KeyA]: ['ф', 'Ф'],
        [Key.KeyS]: ['ы', 'Ы'],
        [Key.KeyD]: ['в', 'В'],
        [Key.KeyF]: ['а', 'А'],
        [Key.KeyG]: ['п', 'П'],
        [Key.KeyH]: ['р', 'Р'],
        [Key.KeyJ]: ['о', 'О'],
        [Key.KeyK]: ['л', 'Л'],
        [Key.KeyL]: ['д', 'Д'],
        [Key.Semicolon]: ['ж', 'Ж'],
        [Key.Quote]: ['э', 'Э'],
        [Key.Backslash]: ['\\', '/'],

        [Key.ShiftRight]: [
            'Ё',
            '!',
            '"',
            '№',
            ';',
            '%',
            'Й',
            'Ц',
            'У',
            'К',
            'Е',
            'Ф',
            'Ы',
            'В',
            'А',
            'П',
            '[',
            'Я',
            'Ч',
            'С',
            'М',
            'И'
        ],
        [Key.Backquote]: [']', '['],
        [Key.KeyZ]: ['я', 'Я'],
        [Key.KeyX]: ['ч', 'Ч'],
        [Key.KeyC]: ['с', 'С'],
        [Key.KeyV]: ['м', 'М'],
        [Key.KeyB]: ['и', 'И'],
        [Key.KeyN]: ['т', 'Т'],
        [Key.KeyM]: ['ь', 'Ь'],
        [Key.Comma]: ['б', 'Б'],
        [Key.Period]: ['ю', 'Ю'],
        [Key.Slash]: ['.', ','],
        [Key.ShiftLeft]: [
            ':',
            '?',
            '*',
            '(',
            ')',
            '_',
            '+',
            'Н',
            'Г',
            'Ш',
            'Щ',
            'З',
            'Х',
            'Ъ',
            'Р',
            'О',
            'Л',
            'Д',
            'Ж',
            'Э',
            '/',
            'Т',
            'Ь',
            'Б',
            'Ю',
            ','
        ],

        [Key.Space]: [' ']
    },
    [LOCALE.UK]: {
        [Key.IntlBackslash]: ['\\', '/'],
        [Key.Digit1]: ['1', '!'],
        [Key.Digit2]: ['2', '"'],
        [Key.Digit3]: ['3', '№'],
        [Key.Digit4]: ['4', ';'],
        [Key.Digit5]: ['5', '%'],
        [Key.Digit6]: ['6', ':'],
        [Key.Digit7]: ['7', '?'],
        [Key.Digit8]: ['8', '*'],
        [Key.Digit9]: ['9', '('],
        [Key.Digit0]: ['0', ')'],
        [Key.Minus]: ['-', '_'],
        [Key.Equal]: ['=', '+'],

        [Key.KeyQ]: ['й', 'Й'],
        [Key.KeyW]: ['ц', 'Ц'],
        [Key.KeyE]: ['у', 'У'],
        [Key.KeyR]: ['к', 'К'],
        [Key.KeyT]: ['е', 'Е'],
        [Key.KeyY]: ['н', 'Н'],
        [Key.KeyU]: ['г', 'Г'],
        [Key.KeyI]: ['ш', 'Ш'],
        [Key.KeyO]: ['щ', 'Щ'],
        [Key.KeyP]: ['з', 'З'],
        [Key.BracketLeft]: ['х', 'Х'],
        [Key.BracketRight]: ['ї', 'Ї'],

        [Key.KeyA]: ['ф', 'Ф'],
        [Key.KeyS]: ['і', 'І'],
        [Key.KeyD]: ['в', 'В'],
        [Key.KeyF]: ['а', 'А'],
        [Key.KeyG]: ['п', 'П'],
        [Key.KeyH]: ['р', 'Р'],
        [Key.KeyJ]: ['о', 'О'],
        [Key.KeyK]: ['л', 'Л'],
        [Key.KeyL]: ['д', 'Д'],
        [Key.Semicolon]: ['ж', 'Ж'],
        [Key.Quote]: ['є', 'Є'],
        [Key.Backslash]: ['ʼ', '₴'],

        [Key.ShiftRight]: [
            '/',
            '!',
            '"',
            '№',
            ';',
            '%',
            'Й',
            'Ц',
            'У',
            'К',
            'Е',
            'Ф',
            'І',
            'В',
            'А',
            'П',
            'Ґ',
            'Я',
            'Ч',
            'С',
            'М',
            'И'
        ],
        [Key.Backquote]: ['ґ', 'Ґ'],
        [Key.KeyZ]: ['я', 'Я'],
        [Key.KeyX]: ['ч', 'Ч'],
        [Key.KeyC]: ['с', 'С'],
        [Key.KeyV]: ['м', 'М'],
        [Key.KeyB]: ['и', 'И'],
        [Key.KeyN]: ['т', 'Т'],
        [Key.KeyM]: ['ь', 'Ь'],
        [Key.Comma]: ['б', 'Б'],
        [Key.Period]: ['ю', 'Ю'],
        [Key.Slash]: ['.', ','],
        [Key.ShiftLeft]: [
            ':',
            '?',
            '*',
            '(',
            ')',
            '_',
            '+',
            'Н',
            'Г',
            'Ш',
            'Щ',
            'З',
            'Х',
            'Ї',
            'Р',
            'О',
            'Л',
            'Д',
            'Ж',
            'Є',
            '₴',
            'Т',
            'Ь',
            'Б',
            'Ю',
            ','
        ],

        [Key.Space]: [' ']
    }
};
