name: Build
on: 
  push: 
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: 'windows', image: 'windows-latest' },
            { name: 'macos', image: 'macos-latest' },
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Publish app
        env:
          VITE_NONCE: ${{ secrets.VITE_NONCE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
        run: npm run publish