name: Build
on: 
  push: 
    branches:
      - main
jobs:
  build-macos:
    runs-on: 'macos-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Add MacOS certs
        env:
          MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
          MACOS_CERT_PASSWORD: ''
        run: chmod +x tools/add-osx-cert.sh && . ./tools/add-osx-cert.sh
      - name: Build app
        env:
          VITE_NONCE: ${{ secrets.VITE_NONCE }}
        run: npm run build
      - name: Publish app
        env:
          VITE_NONCE: ${{ secrets.VITE_NONCE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          CI: true
        run: npm run publish